- name: Delete a user if exists
  hosts: otherserver
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include user deletion tasks
      include_tasks: tasks/main.yml
  handlers:
    - import_tasks: handlers/main.yml

